version: '3.8'

services:
  angular-app:
    build: .
    container_name: angular-dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "4200:4200"
    environment:
      - NODE_ENV=development
    command: ng serve --host 0.0.0.0 --poll=2000
